export const dataParcelas = [
  {
    image: "/img/training/recursos/2.jpg",
    modulo: "Actopan",
    municipio: "San Salvador",
    localidad: "El Rodrigo",
    productor: "Julio Hugo Sánchez Quiróz",
    utmEste: "498280.118",
    utmNorte: "2243779.884",
    cultivo: "Alfalfa",
    sistema: "Riego por aspersión",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.9m Rectangular",
  },
  {
    image: "/img/training/recursos/1.jpg",
    modulo: "Actopan",
    municipio: "Actopan",
    localidad: "Cuauhtémoc",
    productor: "Joel Cruz Núñez",
    utmEste: "503445.766",
    utmNorte: "2234915.616",
    cultivo: "Maíz",
    sistema: "Riego por multicompuertas",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.9m Rectangular",
  },
  {
    image: "/img/training/recursos/3.jpg",
    modulo: "Actopan",
    municipio: "Actopan",
    localidad: "El Huaxtho",
    productor: "Enrique Cortes Vázquez",
    utmEste: "505220.103",
    utmNorte: "2238018.383",
    cultivo: "Frijol",
    sistema: "Riego por goteo",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.9m Rectangular",
  },
  {
    image: "/img/training/recursos/4.jpg",
    modulo: "Actopan",
    municipio: "El Arenal",
    localidad: "El Jiadi",
    productor: "Sebastián Oropeza Baltazar",
    utmEste: "504559.179",
    utmNorte: "2235600.322",
    cultivo: "Maíz",
    sistema: "Riego por multicompuertas",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.9m Rectangular",
  },
  {
    image: "/img/training/recursos/5.jpg",
    modulo: "Actopan",
    municipio: "San Salvador",
    localidad: "Caxuxi",
    productor:
      "Eduardo David Martínez García / Lorenzo Martínez García",
    utmEste: "501157.898",
    utmNorte: "2245646.330",
    cultivo: "Alfalfa",
    sistema: "Riego por aspersión",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.9m Rectangular",
  },
  {
    image: "/img/training/recursos/6.jpg",
    modulo: "Actopan",
    municipio: "Santiago de Anaya",
    localidad: "Cerritos",
    productor: "Oscar Aldana Paredes",
    utmEste: "498729.844",
    utmNorte: "2250921.035",
    cultivo: "Alfalfa",
    sistema: "Riego por aspersión",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.9m Rectangular",
  },
  {
    image: "/img/training/recursos/7.jpg",
    modulo: "Alfajayucan",
    municipio: "Alfajayucan",
    localidad: "Boxtho",
    productor: "Gabino Fuentes Trejo",
    utmEste: "459735.527",
    utmNorte: "2260220.282",
    cultivo: "Maíz/Hortalizas",
    sistema: "Riego por multicompuertas",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.6m Rectangular",
  },
  {
    image: "/img/training/recursos/8.jpg",
    modulo: "Alfajayucan",
    municipio: "Alfajayucan",
    localidad: "Bienes Comunales Thaxie",
    productor: "Yolanda Cruz Francisco",
    utmEste: "466307.528",
    utmNorte: "2259906.972",
    cultivo: "Maíz",
    sistema: "Riego por multicompuertas",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.6m Rectangular",
  },
  {
    image: "/img/training/recursos/9.jpg",
    modulo: "Alfajayucan",
    municipio: "Alfajayucan",
    localidad: "Santa María Xingui",
    productor: "Gustavo Medina Benitez",
    utmEste: "465101.070",
    utmNorte: "2264082.175",
    cultivo: "Maíz",
    sistema: "Riego por goteo",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.6m Rectangular",
  },
  {
    image: "/img/training/recursos/10.jpg",
    modulo: "Alfajayucan",
    municipio: "Alfajayucan",
    localidad: "La Cruz",
    productor: "Sebastián Zamudio Castillo",
    utmEste: "459933.124",
    utmNorte: "2254206.799",
    cultivo: "Chile/Maíz",
    sistema: "Riego por goteo",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.6m Rectangular",
  },
  {
    image: "/img/training/recursos/11.jpg",
    modulo: "Alfajayucan",
    municipio: "Alfajayucan",
    localidad: "La vega",
    productor: "Elvia Beltran Trejo",
    utmEste: "464505.877",
    utmNorte: "2265397.584",
    cultivo: "Maíz",
    sistema: "Riego por multicompuertas",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.6m Rectangular",
  },
  {
    image: "/img/training/recursos/12.jpg",
    modulo: "Alfajayucan",
    municipio: "Alfajayucan",
    localidad: "El Deca",
    productor: "Grupo de Innovación El Deca",
    utmEste: "464517.391",
    utmNorte: "2265457.124",
    cultivo: "Chile/Maíz",
    sistema: "Riego por multicompuertas",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.6m Rectangular",
  },
  {
    image: "/img/training/recursos/13.jpg",
    modulo: "Alfajayucan",
    municipio: "Alfajayucan",
    localidad: "La cruz Baxthe",
    productor: "Ricardo Antonio Saldivar",
    utmEste: "460025.201",
    utmNorte: "2253969.953",
    cultivo: "Maíz",
    sistema: "Riego por goteo",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.6m Rectangular",
  },
  {
    image: "/img/training/recursos/14.jpg",
    modulo: "Alfajayucan",
    municipio: "Alfajayucan",
    localidad: "Santa María La Palma",
    productor: "Esteban Zamudio Castillo",
    utmEste: "460218.539",
    utmNorte: "2254034.048",
    cultivo: "Maíz",
    sistema: "Riego por multicompuertas",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.9m Rectangular",
  },
  {
    image: "/img/training/recursos/15.jpg",
    modulo: "Alfajayucan",
    municipio: "Alfajayucan",
    localidad: "Yonthe Grande",
    productor: "Humberto Torres Concepción",
    utmEste: "461623.478",
    utmNorte: "2262905.619",
    cultivo: "Maíz",
    sistema: "Riego por multicompuertas",
    canaleta: "Sin Revestir",
    dimensiones: "1.0m X 0.9m Rectangular",
  },
  
];
