export const dataParcelas = [
  {
    imgParcela: "/img/parcelas demostrativas/1.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Actopan.png",
    distrito: "003 Tula",
    modulo: "Organización Productora Agricola y Ganadera de las Aguas para Riego, A.C.  (Modulo 1,  Actopan.)",
    municipio: "Actopan",
    localidad: "El Huaxtho",
    cultivo: "Frijol",
    latitud: "20.2400078969872",
    longitud: "-98.9500265941018",
    modalidad: "Por goteo",
    llegarTierra: "Por definir",
    // parcelas
    name: "Actopan - El Huaxtho",
    description: "Cultivo: Frijol. Modalidad: Por goteo",
    bg: "/img/parcelas demostrativas/1.jpg",
    link: "/parcelas/actopan-el-huaxtho",
  },
  {
    imgParcela: "/img/parcelas demostrativas/2.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Mixquiahuala de Juárez.png",
    distrito: "003 Tula",
    modulo: "Usuarios de Riego del Sistema Endho Xochitlán",
    municipio: "Mixquiahuala de Juárez",
    localidad: "El Llano",
    cultivo: "Por definir",
    latitud: "20.2464583142766",
    longitud: "-99.1601430964357",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Mixquiahuala de Juárez - El Llano",
    description: "Cultivo: Por definir. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/2.jpg",
    link: "/parcelas/mixquiahuala-de-juárez-el-llano",
  },
  {
    imgParcela: "/img/parcelas demostrativas/3.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Progreso de Obregón.png",
    distrito: "003 Tula",
    modulo: "Usuarios de Riego del Sistema Endho Xochitlán",
    municipio: "Progreso de Obregón",
    localidad: "Bombeo Ejido Progreso",
    cultivo: "Maíz",
    latitud: "20.2662247688979",
    longitud: "-99.149867019836",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Progreso de Obregón - Bombeo Ejido Progreso",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/3.jpg",
    link: "/parcelas/progreso-de-obregón-bombeo-ejido-progreso",
  },
  {
    imgParcela: "/img/parcelas demostrativas/4.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Progreso de Obregón.png",
    distrito: "003 Tula",
    modulo: "Usuarios de Riego del Sistema Endho Xochitlán, A.C.",
    municipio: "Progreso de Obregón",
    localidad: "Colonia Veracruz",
    cultivo: "Chile",
    latitud: "20.2643217613864",
    longitud: "-99.1497320590921",
    modalidad: "Multicompuertas",
    llegarTierra: "Por definir",
    // parcelas
    name: "Progreso de Obregón - Colonia Veracruz",
    description: "Cultivo: Chile. Modalidad: Multicompuertas",
    bg: "/img/parcelas demostrativas/4.jpg",
    link: "/parcelas/progreso-de-obregón-colonia-veracruz",
  },
  {
    imgParcela: "/img/parcelas demostrativas/5.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Progreso de Obregón.png",
    distrito: "003 Tula",
    modulo: "Usuarios de Riego del Sistema Endho Xochitlán",
    municipio: "Progreso de Obregón",
    localidad: "Palma Gorda",
    cultivo: "Maíz",
    latitud: "20.2579282201923",
    longitud: "-99.1629672034536",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Progreso de Obregón - Palma Gorda",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/5.jpg",
    link: "/parcelas/progreso-de-obregón-palma-gorda",
  },
  {
    imgParcela: "/img/parcelas demostrativas/6.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Progreso de Obregón.png",
    distrito: "003 Tula",
    modulo: "Usuarios de Riego del Sistema Endho Xochitlán",
    municipio: "Progreso de Obregón",
    localidad: "Xamu",
    cultivo: "Maíz",
    latitud: "20.2642978265172",
    longitud: "-99.1736590623628",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Progreso de Obregón - Xamu",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/6.jpg",
    link: "/parcelas/progreso-de-obregón-xamu",
  },
  {
    imgParcela: "/img/parcelas demostrativas/7.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/San Salvador.png",
    distrito: "003 Tula",
    modulo: "Organización Productora Agricola y Ganadera de las Aguas para Riego, A.C.  (Modulo 1,  Actopan.)",
    municipio: "San Salvador",
    localidad: "Cañada Grande",
    cultivo: "Maíz",
    latitud: "20.3075882825519",
    longitud: "-98.9982757180456",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "San Salvador - Cañada Grande",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/7.jpg",
    link: "/parcelas/san-salvador-cañada-grande",
  },
  {
    imgParcela: "/img/parcelas demostrativas/8.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/San Salvador.png",
    distrito: "003 Tula",
    modulo: "Organización Productora Agricola y Ganadera de las Aguas para Riego, A.C.  (Modulo 1,  Actopan.)",
    municipio: "San Salvador",
    localidad: "Carr San Salvador-Caxuxi",
    cultivo: "Alfalfa",
    latitud: "20.2945417754303",
    longitud: "-99.0033392416719",
    modalidad: "Multicompuertas",
    llegarTierra: "Por definir",
    // parcelas
    name: "San Salvador - Carr San Salvador-Caxuxi",
    description: "Cultivo: Alfalfa. Modalidad: Multicompuertas",
    bg: "/img/parcelas demostrativas/8.jpg",
    link: "/parcelas/san-salvador-carr-san-salvador-caxuxi",
  },
  {
    imgParcela: "/img/parcelas demostrativas/9.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/San Salvador.png",
    distrito: "003 Tula",
    modulo: "Organización Productora Agricola y Ganadera de las Aguas para Riego, A.C.  (Modulo 1,  Actopan.)",
    municipio: "San Salvador",
    localidad: "Tothie La 23",
    cultivo: "Maíz",
    latitud: "20.247549394849",
    longitud: "-99.0126232110193",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "San Salvador - Tothie La 23",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/9.jpg",
    link: "/parcelas/san-salvador-tothie-la-23",
  },
  {
    imgParcela: "/img/parcelas demostrativas/10.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/San Salvador.png",
    distrito: "003 Tula",
    modulo: "Organización Productora Agricola y Ganadera de las Aguas para Riego, A.C.  (Modulo 1,  Actopan.)",
    municipio: "San Salvador",
    localidad: "Tothie La 23",
    cultivo: "Maíz",
    latitud: "20.247560452574",
    longitud: "-99.0120535630165",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "San Salvador - Tothie La 23",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/10.jpg",
    link: "/parcelas/san-salvador-tothie-la-23-2",
  },
  {
    imgParcela: "/img/parcelas demostrativas/11.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Tezontepec de Aldama.png",
    distrito: "003 Tula",
    modulo: "Asociacion de Campesinos, Sección 45 El Solís, A.C.",
    municipio: "Tezontepec de Aldama",
    localidad: "El Solis",
    cultivo: "Maíz",
    latitud: "20.1060650406588",
    longitud: "-99.2767045482768",
    modalidad: "Multicompuertas",
    llegarTierra: "Por definir",
    // parcelas
    name: "Tezontepec de Aldama - El Solis",
    description: "Cultivo: Maíz. Modalidad: Multicompuertas",
    bg: "/img/parcelas demostrativas/11.jpg",
    link: "/parcelas/tezontepec-de-aldama-el-solis",
  },
  {
    imgParcela: "/img/parcelas demostrativas/12.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Tlahuelilpan.png",
    distrito: "003 Tula",
    modulo: "Tlamaco-Juandho",
    municipio: "Tlahuelilpan",
    localidad: "San Primitivo",
    cultivo: "Por definir",
    latitud: "20.1123323274542",
    longitud: "-99.221737932254",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Tlahuelilpan - San Primitivo",
    description: "Cultivo: Por definir. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/12.jpg",
    link: "/parcelas/tlahuelilpan-san-primitivo",
  },
  {
    imgParcela: "/img/parcelas demostrativas/13.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Tlaxcoapan.png",
    distrito: "003 Tula",
    modulo: "Asociación Civil \"Bombeo Agrícola Teltipán, A.C.\"",
    municipio: "Tlaxcoapan",
    localidad: "Ejido Teltipan de Juárez",
    cultivo: "Maíz",
    latitud: "20.097520578669",
    longitud: "-99.1791989820785",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Tlaxcoapan - Ejido Teltipan de Juárez",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/13.jpg",
    link: "/parcelas/tlaxcoapan-ejido-teltipan-de-juárez",
  },
  {
    imgParcela: "/img/parcelas demostrativas/14.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Tlaxcoapan.png",
    distrito: "003 Tula",
    modulo: "Asociación Civil \"Bombeo Agrícola Teltipán, A.C.\"",
    municipio: "Tlaxcoapan",
    localidad: "Ejido Teltipan de Juárez",
    cultivo: "Maíz",
    latitud: "20.1093310070382",
    longitud: "-99.1888665562093",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Tlaxcoapan - Ejido Teltipan de Juárez",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/14.jpg",
    link: "/parcelas/tlaxcoapan-ejido-teltipan-de-juárez-2",
  },
  {
    imgParcela: "/img/parcelas demostrativas/15.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Tlaxcoapan.png",
    distrito: "003 Tula",
    modulo: "Asociación Civil \"Bombeo Agrícola Teltipán, A.C.\"",
    municipio: "Tlaxcoapan",
    localidad: "Teltipán de Juárez",
    cultivo: "Maíz",
    latitud: "20.0985872877072",
    longitud: "-99.1791811986663",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Tlaxcoapan - Teltipán de Juárez",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/15.jpg",
    link: "/parcelas/tlaxcoapan-teltipán-de-juárez",
  },
  {
    imgParcela: "/img/parcelas demostrativas/1.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Alfajayucan.png",
    distrito: "100 Alfajayucan",
    modulo: "Asociación de usuarios de riego Alfajayucan A.C.",
    municipio: "Alfajayucan",
    localidad: "Ejido Zozea",
    cultivo: "Maíz",
    latitud: "20.4324791507273",
    longitud: "-99.3809455810311",
    modalidad: "Trituración",
    llegarTierra: "Por definir",
    // parcelas
    name: "Alfajayucan - Ejido Zozea",
    description: "Cultivo: Maíz. Modalidad: Trituración",
    bg: "/img/parcelas demostrativas/1.jpg",
    link: "/parcelas/alfajayucan-ejido-zozea",
  },
  {
    imgParcela: "/img/parcelas demostrativas/2.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Alfajayucan.png",
    distrito: "100 Alfajayucan",
    modulo: "Asociación de usuarios de riego Alfajayucan A.C.",
    municipio: "Alfajayucan",
    localidad: "Naxthéy",
    cultivo: "Maíz",
    latitud: "20.4457966644316",
    longitud: "-99.3300862476415",
    modalidad: "Trituración",
    llegarTierra: "Por definir",
    // parcelas
    name: "Alfajayucan - Naxthéy",
    description: "Cultivo: Maíz. Modalidad: Trituración",
    bg: "/img/parcelas demostrativas/2.jpg",
    link: "/parcelas/alfajayucan-naxthéy",
  },
  {
    imgParcela: "/img/parcelas demostrativas/3.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Alfajayucan.png",
    distrito: "100 Alfajayucan",
    modulo: "Asociación de Usuarios de Riego Unidad Alfajayucan, A.C.",
    municipio: "Alfajayucan",
    localidad: "Santa María Xingui",
    cultivo: "Maíz",
    latitud: "20.4751741771879",
    longitud: "-99.3346198851891",
    modalidad: "Por goteo",
    llegarTierra: "Por definir",
    // parcelas
    name: "Alfajayucan - Santa María Xingui",
    description: "Cultivo: Maíz. Modalidad: Por goteo",
    bg: "/img/parcelas demostrativas/3.jpg",
    link: "/parcelas/alfajayucan-santa-maría-xingui",
  },
  {
    imgParcela: "/img/parcelas demostrativas/4.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Alfajayucan.png",
    distrito: "100 Alfajayucan",
    modulo: "Asociación de usuarios de riego Alfajayucan A.C.",
    municipio: "Alfajayucan",
    localidad: "Taxhie",
    cultivo: "Maíz",
    latitud: "20.4360502068743",
    longitud: "-99.3221374688268",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Alfajayucan - Taxhie",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/4.jpg",
    link: "/parcelas/alfajayucan-taxhie",
  },
  {
    imgParcela: "/img/parcelas demostrativas/5.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Alfajayucan.png",
    distrito: "100 Alfajayucan",
    modulo: "Asociación de usuarios de riego Alfajayucan A.C.",
    municipio: "Alfajayucan",
    localidad: "Yonthe Grande  \"La Mina\"",
    cultivo: "Maíz",
    latitud: "20.4765613068054",
    longitud: "-99.3704461684247",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Alfajayucan - Yonthe Grande \"La Mina\"",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/5.jpg",
    link: "/parcelas/alfajayucan-yonthe-grande-la-mina",
  },
  {
    imgParcela: "/img/parcelas demostrativas/6.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Chilcuautla.png",
    distrito: "100 Alfajayucan",
    modulo: "Usuarios de Riego Canal del Centro, A.C.",
    municipio: "Chilcuautla",
    localidad: "El Cerrito",
    cultivo: "Maíz",
    latitud: "20.3211893492503",
    longitud: "-99.2333562633961",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Chilcuautla - El Cerrito",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/6.jpg",
    link: "/parcelas/chilcuautla-el-cerrito",
  },
  {
    imgParcela: "/img/parcelas demostrativas/7.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Chilcuautla.png",
    distrito: "100 Alfajayucan",
    modulo: "Usuarios de Riego Canal del Centro, A.C.",
    municipio: "Chilcuautla",
    localidad: "Zacualoya",
    cultivo: "Maíz",
    latitud: "20.3599447516643",
    longitud: "-99.2348960615482",
    modalidad: "Multicompuertas",
    llegarTierra: "Por definir",
    // parcelas
    name: "Chilcuautla - Zacualoya",
    description: "Cultivo: Maíz. Modalidad: Multicompuertas",
    bg: "/img/parcelas demostrativas/7.jpg",
    link: "/parcelas/chilcuautla-zacualoya",
  },
  {
    imgParcela: "/img/parcelas demostrativas/8.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Ixmiquilpan.png",
    distrito: "100 Alfajayucan",
    modulo: "Zona de Riego Tasquillo, A.C.",
    municipio: "Ixmiquilpan",
    localidad: "Loma López Rayón",
    cultivo: "Maíz",
    latitud: "20.4903903126361",
    longitud: "-99.2603247479562",
    modalidad: "Multicompuertas",
    llegarTierra: "Por definir",
    // parcelas
    name: "Ixmiquilpan - Loma López Rayón",
    description: "Cultivo: Maíz. Modalidad: Multicompuertas",
    bg: "/img/parcelas demostrativas/8.jpg",
    link: "/parcelas/ixmiquilpan-loma-lópez-rayón",
  },
  {
    imgParcela: "/img/parcelas demostrativas/9.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Tasquillo.png",
    distrito: "100 Alfajayucan",
    modulo: "Asociacion Civil, Riego Zona Tasquillo A.C.",
    municipio: "Tasquillo",
    localidad: "López Rayón",
    cultivo: "Maíz",
    latitud: "20.4843843313483",
    longitud: "-99.2668626603747",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Tasquillo - López Rayón",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/9.jpg",
    link: "/parcelas/tasquillo-lópez-rayón",
  },
  {
    imgParcela: "/img/parcelas demostrativas/10.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Ajacuba.png",
    distrito: "112 Ajacuba",
    modulo: "Asociación de Usuarios Valle de Ajacuba, A.C.",
    municipio: "Ajacuba",
    localidad: "San Nicolás Tecomatlán",
    cultivo: "Maíz",
    latitud: "20.1517341385173",
    longitud: "-99.0397333798128",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Ajacuba - San Nicolás Tecomatlán",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/10.jpg",
    link: "/parcelas/ajacuba-san-nicolás-tecomatlán",
  },
  {
    imgParcela: "/img/parcelas demostrativas/11.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Ajacuba.png",
    distrito: "112 Ajacuba",
    modulo: "Asociación de Usuarios Valle de Ajacuba, A.C.",
    municipio: "Ajacuba",
    localidad: "San Nicolás Tecomatlán",
    cultivo: "Maíz",
    latitud: "20.1487210879543",
    longitud: "-99.035092824194",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Ajacuba - San Nicolás Tecomatlán",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/11.jpg",
    link: "/parcelas/ajacuba-san-nicolás-tecomatlán-2",
  },
  {
    imgParcela: "/img/parcelas demostrativas/12.jpg",
    imgMunicipio: "/img/parcelas demostrativas/municipios/Ajacuba.png",
    distrito: "112 Ajacuba",
    modulo: "Asociación de Usuarios Valle de Ajacuba, A.C.",
    municipio: "Ajacuba",
    localidad: "Santiago Tezontlale",
    cultivo: "Maíz",
    latitud: "20.1520043493313",
    longitud: "-99.0401627713677",
    modalidad: "Nivelación",
    llegarTierra: "Por definir",
    // parcelas
    name: "Ajacuba - Santiago Tezontlale",
    description: "Cultivo: Maíz. Modalidad: Nivelación",
    bg: "/img/parcelas demostrativas/12.jpg",
    link: "/parcelas/ajacuba-santiago-tezontlale",
  },
];
