export const dataSuppliers = [
  {
    "id": 1,
    "Empresa": "Maquinas Diesel S.A. de C.V. (Madisa CAT)",
    "Giro": "Maquinaria y equipo agrícola",
    "Contacto": "771 129 0924",
    "NumParcelas": 20,
    "bg": "/img/parcelasDemostrativas/2.jpg",
  },
  {
    "id": 2,
    "Empresa": "Casa Agricola del Campesino de Ixmiquilpan S. A. de C.V.",
    "Giro": "Maquinaria y equipo agrícola",
    "Contacto": "771 202 3573",
    "NumParcelas": 15,
    "bg": "/img/parcelasDemostrativas/3.jpg",
  },
  {
    "id": 3,
    "Empresa": "GIMTRAC S.A. de C.V. John Deere",
    "Giro": "Maquinaria y equipo agrícola",
    "Contacto": "771 747 3636",
    "NumParcelas": 5,
    "bg": "/img/parcelasDemostrativas/4.jpg",
  },
  {
    "id": 4,
    "Empresa": "Cadena",
    "Giro": "Sistemas de riego",
    "Contacto": "771 129 2849",
    "NumParcelas": 19,
    "bg": "/img/parcelasDemostrativas/5.jpg",
  },
  {
    "id": 5,
    "Empresa": "Jardinería y Agua Azul S.A. de C.V.",
    "Giro": "Construcción de sistemas agrícola de riego",
    "Contacto": "554 322 4032",
    "NumParcelas": 4,
    "bg": "/img/parcelasDemostrativas/6.jpg",
  },
  {
    "id": 6,
    "Empresa": "Agroindustrias GAR S.C. de R.L. de C.V.",
    "Giro": "Equipo de riego",
    "Contacto": "442 338 1997",
    "NumParcelas": 3,
    "bg": "/img/parcelasDemostrativas/7.jpg",
  },
  {
    "id": 7,
    "Empresa": "Ingeniería e Infraestructura Hidroagrícola S.A. de C.V. (HIDROIN)",
    "Giro": "Sistemas de riego",
    "Contacto": "595 952 8527",
    "NumParcelas": 2,
    "bg": "/img/parcelasDemostrativas/8.jpg",
  },
  {
    "id": 8,
    "Empresa": "Proyectos y Estudios Hidrosustentables S.A. de C.V.",
    "Giro": "Sistemas de Riego",
    "Contacto": "2462946069",
    "NumParcelas": 3,
    "bg": "/img/parcelasDemostrativas/9.jpg",
  },
  {
    "id": 9,
    "Empresa": "Serviriego S.A de C.V.",
    "Giro": "Sistemas de Riego",
    "Contacto": "7751063743",
    "NumParcelas": 2,
    "bg": "/img/parcelasDemostrativas/10.jpg",
  },
  {
    "id": 10,
    "Empresa": "Cadena Comercial Vysne S. de R.L. de C.V. Agroservicios La Aduana",
    "Giro": "Sistemas de riego",
    "Contacto": "777 103 2457",
    "NumParcelas": 2,
    "bg": "/img/parcelasDemostrativas/11.jpg",
  },
  {
    "id": 11,
    "Empresa": "Soluciones Integrales (SOLCAM)",
    "Giro": "Sistemas de Riego",
    "Contacto": "771 236 5624",
    "NumParcelas": 1,
    "bg": "/img/parcelasDemostrativas/12.jpg",
  },
  {
    "id": 12,
    "Empresa": "Grupo PADIHER S.A. de C.V.",
    "Giro": "Sistemas de Riego",
    "Contacto": "553 221 7496",
    "NumParcelas": 1,
    "bg": "/img/parcelasDemostrativas/13.jpg",
  },
  {
    "id": 13,
    "Empresa": "Fertilex S.A. de C.V.",
    "Giro": "Insumos, reforestación e información satelital",
    "Contacto": "771 772 9792",
    "NumParcelas": 10,
    "bg": "/img/parcelasDemostrativas/14.jpg",
  },
  {
    "id": 14,
    "Empresa": "Comercializadora MEGASEM Semillas Aspros",
    "Giro": "Insumos agrícolas",
    "Contacto": "461 254 3285",
    "NumParcelas": 50,
    "bg": "/img/parcelasDemostrativas/15.jpg",
  },
  {
    "id": 15,
    "Empresa": "Palacios Integradora Agropecuaria",
    "Giro": "Insumos agrícolas",
    "Contacto": "771 716 3652",
    "NumParcelas": 8,
    "bg": "/img/parcelasDemostrativas/16.jpg",
  },
  {
    "id": 16,
    "Empresa": "GEOSPHERA",
    "Giro": "Consultoría Y Proveeduría Agrícola",
    "Contacto": "771 220 9086",
    "NumParcelas": 6,
    "bg": "/img/parcelasDemostrativas/17.jpg",
  },
  {
    "id": 17,
    "Empresa": "Grupo PADIHER S.A. de C.V.",
    "Giro": "Insumos agrícolas",
    "Contacto": "461 108 7256",
    "NumParcelas": 6,
    "bg": "/img/parcelasDemostrativas/18.jpg",
  },
  {
    "id": 18,
    "Empresa": "Servicios Técnicos Agrícolas",
    "Giro": "Insumos agrícolas",
    "Contacto": "221 348 8452",
    "NumParcelas": 28,
    "bg": "/img/parcelasDemostrativas/19.jpg",

  }
]
